name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and zip
        run: |
          mkdir build
          pip install -r requirements.txt -t build/
          cp lambda_handler.py build/
          cd build && zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ca-central-1'
        run: |
          # Deploy the Lambda function
          aws lambda update-function-code \
            --function-name LAMBDA-FUNCTION \
            --zip-file fileb://lambda.zip \
            --region $AWS_REGION

          # Create or update Lambda URL
          # Replace this with the correct Lambda function name and URL configuration
          aws lambda add-function-url-permission \
            --function-name LAMBDA-FUNCTION \
            --principal '*' \
            --statement-id "lambda-deploy-$(date +%s)" \
            --region $AWS_REGION

          # Optionally, output the Lambda URL
          URL=$(aws lambda get-function-url --function-name LAMBDA-FUNCTION --region $AWS_REGION --query 'FunctionUrl' --output text)
          echo "Lambda function URL: $URL"

